### ISSUE TITLE
[Bug]: Horse flew through air after getting kicked

### ISSUE THREAD

**Issue by NextheBestest** [cavecomputing/SWEM-Beta#10]
### What happened?

As I was riding a horse and it bucked near another horse, the other horse got kicked/hurt by it and flew off into the distance a few hundred blocks away.

### What should happen?

The horse should not fly that far after getting kicked.

### Mods

SWEM and geckolib

### SWEM Version

1.16.5-0.1.0.0-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by NextheBestest** [comment]
Happened again in 0.1.1.1-b, and it happened when horses were in a big group

**Comment by NextheBestest** [comment]
Still happening in 0.1.3.0-b, steps to reproduce; get a bunch of horses in an enclosed area (i used fences) then hit one of them and that made them start kicking other horses then they all fly over the area, although they are stopped from going really far because of the fences

**Comment by MagnusHJensen** [comment]
This has been fixed.
