### ISSUE TITLE
[Bug]: horse glitching out after jumping

### ISSUE THREAD

**Issue by dronade** [cavecomputing/SWEM-Beta#102]
### What happened?

https://drive.google.com/file/d/1NQdyfg2_sYnT76ocwwKAToqrznFAN4sU/view
https://drive.google.com/file/d/1pjcy97j2nmn-B7NDYCk8Xj7Zi_TNrpJY/view?usp=sharing
^ vids of glitch happening

mostly occurs when landing after a jump and immediately going up a block at the same time but as seen in the second vid it also happens sometimes when going up a block in canter
when it does happen it stops you going forward until you break out of the glitch (how I've found to break out if it is to turn on the spot or sidestep)

### What should happen?

smooth landing

### Mods

swem + geckolib

### SWEM Version

0.1.2.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
We will see what options we have, but there isn't much we can do, since it's a case of minecrafts movement logic, and our high speed for max leveled horses.
