### ISSUE TITLE
[Bug]: Flashing and disappearing pee puddles 

### ISSUE THREAD

**Issue by WildSilverr** [cavecomputing/SWEM-Beta#109]
### What happened?

Once a horse has peed, the pee puddle flashes and disappears depending on mouse placement/ viewing angle
![Pee puddle SWEM](https://user-images.githubusercontent.com/93545930/140593174-40e3d64e-050b-4585-9af4-9dbf34e90e92.png)
.

### What should happen?

Pee puddle should be a solid texture/image  on the ground/block

### Mods

SWEM and GeckoLib

### SWEM Version

1.16.5-0.1.2.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Silverwolf11420** [comment]
I have this problem as well

**Comment by SnowDragon064** [comment]
I am also having this problem, on both multiplayer and singleplayer

**Comment by MagnusHJensen** [comment]
This should hopefully have been fixed with version: `0.2.5.10-b` and up.
