### ISSUE TITLE
[Bug]: Horse's hunger not rising

### ISSUE THREAD

**Issue by Silverwolf11420** [cavecomputing/SWEM-Beta#110]
### What happened?

The horse is eating the quality bales but the hunger bar is not rising. It will just keep eating what is available and still lose hunger 
![2021-11-05_23 35 47](https://user-images.githubusercontent.com/70761126/140598037-5c1cabee-7374-4d81-bc0f-356998b08b7a.png)
![2021-11-05_23 35 59](https://user-images.githubusercontent.com/70761126/140598038-d76980d4-86de-418a-8568-3e5784a90147.png)
!

Steps to reproduce:
1. Set out quality bales
2. Get SWEM horse
3. Wait until hungry

### What should happen?

When the horse eats, it should be getting full instead of starving even though it's eating.

### Mods

geckolib-forge-1.16.5-3.0.35
swem-1.16.5-0.1.2.1-b

### SWEM Version

0.1.2.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Xemoness** [comment]
You can also not hand-feed them with anything. It will not fill up the hunger bar.

**Items I have tried to feed with without any success:**
- Quality bale
- Hay block
- Sweet feed
- Carrot
- Wheat
- Timothy bushel
- Oat bushel
- Alfalfa bushel

**Comment by MagnusHJensen** [comment]
You can hand feed them. I will work on visual feedback for hand feeding, so you know if it failed or not. Or it's correct.

**Comment by MagnusHJensen** [comment]
@Silverwolf11420 Can you double check on `0.1.3.0-b` if this issue still persists, since it fixed a hunger levelup logic issue.

**Comment by Silverwolf11420** [comment]
On 0.1.3.0-b the hunger does go up now by only manually feeding but only to the 3rd level and never full. Only way I have figured out to get a maxed out hunger bar is the dev command
