### ISSUE TITLE
[Bug]: Crashing when creating world

### ISSUE THREAD

**Issue by skythebro** [cavecomputing/SWEM-Beta#12]
### What happened?

Created a singleplayer world, difficulty peaceful and right as it generated it crashes, leaving behind a crash report

### What should happen?

The world should load without crashing

### Mods

geckolib-forge-1.16.5-3.0.35
swem-1.16.5-0.1.0.0-b (1)

### SWEM Version

swem-1.16.5-0.1.0.0-b (1)

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
Crash report: https://pastebin.com/RtzKGvNb
```

**Comment by skythebro** [comment]
I have crashed again but now in a totally different world that did get created fully. But after flying around for a couple of seconds this crash happened, it looks familiar to the previous one i had. 
Crash report: https://pastebin.com/uAJx41Da

**Comment by skythebro** [comment]
Loading into the world again spawns me back at where i loaded into the world , flying again to that same spot crashes me again.

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.1.0.2-b` and up.
