### ISSUE TITLE
[Bug]: The /dev maxlevel command not working.

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#122]
### What happened?

The /dev command is not levelling up my horse. I have also tried it on another world and its also not working. 

### What should happen?

The /dev command should level up the horse.

### Mods

Swem 
Gekolib

### SWEM Version

swem-1.16.5-0.1.3.0-b.jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed with version: `0.1.3.4-b` and up.

Make sure you are sitting on the horse while doing the command though.
