### ISSUE TITLE
[Bug]: Low relationship horse not giving  any rear or buck animation 

### ISSUE THREAD

**Issue by EvenBlutoms** [cavecomputing/SWEM-Beta#125]
### What happened?

tried 2 different horses with low relationship stats and don't give any buck or rear animations but keep walking when I press H to speed up 

### What should happen?

Buck or Rear animation with low relationship stated horse

### Mods

Geckolib-forge
Swem-1.16.5-1.3.0

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
No response
```

**Comment by MagnusHJensen** [comment]
Duplicate see #106
