### ISSUE TITLE
[Bug]: Armour Placement on horses

### ISSUE THREAD

**Issue by IcyWhisper21** [cavecomputing/SWEM-Beta#126]
### What happened?

The placement of the head piece for the horse armour and hooves is off. The head piece hovers above the horse and the hoof pieces arent alligned with the actual horse hoof. Also the amethyst armour doesnt move with the horse at all and just kind of stays still, with no animations.

### What should happen?

Armour should fit the horse.

### Mods

None

### SWEM Version

0.1.3.0-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Mac

**Comment by MagnusHJensen** [comment]
The hoof pieces and the two leather head pieces aswell as the "breast" piece, is marked for removal, and substituted with a texture instead of model. In an upcoming version.

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `0.3.6.2-b`
