### ISSUE TITLE
[Bug]: Dogs not harmed when attacking horses

### ISSUE THREAD

**Issue by flokii7** [cavecomputing/SWEM-Beta#132]
### What happened?

https://user-images.githubusercontent.com/86190898/142059993-a3f6dca9-c9d8-4789-ae17-33e651d230bd.mp4

When you hit the horse the dog attacks and the horse bucks, but damage is only dealt to the horse and not the dog.
When in a certain radius of the horse the dog does occasionally take damage, but rarely.

### What should happen?

Both mobs should take damage.

### Mods

Geckolib 3.0.35
SWEM 0.1.6.10-b
(optifine only used for recording)

### SWEM Version

0.1.6.10-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
I can't seem to reproduce, my wolf takes damage, when it bucks.

However I do not know how you made the dog attack the horse xD
