### ISSUE TITLE
[Bug]: Horse gets thrown when led into cactus

### ISSUE THREAD

**Issue by flokii7** [cavecomputing/SWEM-Beta#133]
### What happened?

https://user-images.githubusercontent.com/86190898/142063057-b22ca5de-c821-4738-a39f-f2200fc9c5a6.mp4

When leading a horse into a cactus it gets flung after the buck/rear animation plays. Also occurs when player is not flying.

### What should happen?

Horse should not get catapulted.

### Mods

Geckolib 3.0.35
SWEM 0.1.6.10-b

### SWEM Version

1.16.5-0.1.1.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `0.2.5.27-b` and up.
