### ISSUE TITLE
Game Crashes When Trying To Take A SS In Free-look

### ISSUE THREAD

**Issue by Phoenix615266** [cavecomputing/SWEM-Beta#144]
When you try to take a screenshot while using free-look, the game immediately crashes.

Game version: 1.16.5

Mods:
SWEM Version: 0.2.2.3
Geckolib Version: 3.0.35

**Comment by MagnusHJensen** [comment]
I can't reproduce.
Make sure your screenshot key is not F4 ;)

**Comment by Phoenix615266** [comment]
ooops
