### ISSUE TITLE
Bugged galloping animation

### ISSUE THREAD

**Issue by Xemoness** [cavecomputing/SWEM-Beta#150]
### What happened?

When going from canter into gallop, the canter animation continues playing but the speed increases to a gallop.
Also, the gallop does not seem to ever stop or have a cooldown.
It works in singleplayer.

### What should happen?

The horse should transition into a gallop normally (eg. from canter animation to gallop animation with working cooldowns)

### Mods

https://gyazo.com/3a95748be6c6cf9e3b0e20ff785518ac

### SWEM Version

0.2.3.9-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Are you sure about this, because a new gait was introduced.

So it goes walk - trot - canter - canter ext. - gallop.
Canter and Canter Ext. both play the same canter anim.

**Comment by Xemoness** [comment]
Yeah, that is the case. I just thought mine wouldn't go into gallop because I didn't click the button again :,) I did spam it on my singleplayer so it went into gallop and that cause me to believe that it didn't work in multiplayer. :(

Very sorry about the wrong issue, I just got confused.

**Comment by MagnusHJensen** [comment]
All good!
