### ISSUE TITLE
[Bug]: Horse flinging when dragged into fire

### ISSUE THREAD

**Issue by emafema** [cavecomputing/SWEM-Beta#160]
### What happened?

When dragging a horse into fire with a lead, it flings

https://user-images.githubusercontent.com/93468469/147888050-f5af33bb-e710-41f0-9c1d-c7c73999f916.mov

.

### What should happen?

The horse should stay where it is.

### Mods

Swem, GeckoLib, Fairy Lights, Storage Drawers, Useful Backpacks, InventoryHud, Xaeros Minimap and Worldmap, Optifine 

### SWEM Version

1.16.5-0.2.5.15-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Mac

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `0.2.5.27-b` and up.
