### ISSUE TITLE
[Bug]: Whitewash fence not connecting

### ISSUE THREAD

**Issue by flokii7** [cavecomputing/SWEM-Beta#162]
### What happened?

![2022-01-03_20 07 57](https://user-images.githubusercontent.com/86190898/147975342-cfef7838-b8c9-42dc-a582-187a4695e0e4.png)
Whitewash fence does not connect

### What should happen?

It should connect

### Mods

SWEM
Geckolib

### SWEM Version

0.2.5.15

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Most likely just needing added as an entry in the fences tag @Silverwolf11420

**Comment by Silverwolf11420** [comment]
This has been fixed with version: 0.2.5.27-b and up.
