### ISSUE TITLE
[Bug]: Lily pads make horse stuck

### ISSUE THREAD

**Issue by WildSilverr** [cavecomputing/SWEM-Beta#164]
### What happened?

While traveling in 1 block deep water and/or swimming, lily pads make the horse get stuck and get only get unstuck with a level 3 jump

### What should happen?

Instead maybe have the lily pads break on impact of the horse coming near, like boats. or have the horse treat them like a block they can walk onto

### Mods

![Screenshot 2022-01-04 224006](https://user-images.githubusercontent.com/93545930/148161527-62463a70-3110-4446-90ec-58d18d353399.png)

### SWEM Version

1.16.5-0.2.5.15-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
They get destroyed when you collide with them now! :D
