### ISSUE TITLE
[Bug]: Horse not taming

### ISSUE THREAD

**Issue by Silverwolf11420** [cavecomputing/SWEM-Beta#17]
### What happened?

Horse isn't taming when rode.
1. Spawn vanilla horse
2. convert it to swem horse
3. ride

### What should happen?

You should be able to tame it like vanilla

### Mods

swem-1.16.5-0.1.0.1-b
geckolib-forge-1.16.5-3.0.35

### SWEM Version

0.1.0.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This was fixed with version: `0.1.1.0-b` and up
