### ISSUE TITLE
Adventure saddlepad/saddle

### ISSUE THREAD

**Issue by Everyuki** [cavecomputing/SWEM-Beta#171]
### What happened?

When you put the adventure saddlepad and saddle on the horse, it is fine, but you can but take the saddlepad off (while saddle is on) and it stays as normal. Perhaps you should change this? 

### What should happen?

Saddle should come off/shouldnt be able to take saddlepad off

### Mods

Swem, GeckoLib, Fairy Lights, Storage Drawers, Useful Backpacks, InventoryHud, Xaeros Minimap and Worldmap

### SWEM Version

1.16.5 (newest release as of 1/8/21)

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This has been added with version: `0.2.5.32-b` and up.
