### ISSUE TITLE
[Bug]: Bleacher breaking problem

### ISSUE THREAD

**Issue by emafema** [cavecomputing/SWEM-Beta#172]
### What happened?

When breaking a stacked bleacher (2 or more on top of each other), it only drops one.

### What should happen?

It should drop so many bleachers you stacked.

### Mods

Swem, GeckoLib, Fairy Lights, Storage Drawers, Useful Backpacks, InventoryHud, Xaeros Minimap and Worldmap, Optifine

### SWEM Version

1.16.5-0.2.5.15-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Mac

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `0.2.5.31-b` and up.
