### ISSUE TITLE
Horse armor not returned if armor stand is broken

### ISSUE THREAD

**Issue by Keroaa** [cavecomputing/SWEM-Beta#174]
### What happened?

Upon breaking the stand if the armor isn't removed first it will not be returned to the player

### What should happen?

The armor should drop from the stand

### Mods

SWEM/ Current beta modpack. 

### SWEM Version

0.2.5.15-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
It does drop the armour in survival.
It doesn't drop in creative. That is a common way to do it.
Were you in creative or survival?

**Comment by Keroaa** [comment]
Sorry, just now seeing this, it was in survival on the test server.

**Comment by MagnusHJensen** [comment]
Can't reproduce.
