### ISSUE TITLE
Whitewash trap doors do not return item upon breaking

### ISSUE THREAD

**Issue by Keroaa** [cavecomputing/SWEM-Beta#175]
### What happened?

Whitewash trap doors disappear when destroyed 

### What should happen?

The trap door should drop to be picked up by the player

### Mods

SWEM/ current beta modpack

### SWEM Version

1.16.5-0.2.5.15-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Silverwolf11420** [comment]
This has been fixed with version: 0.2.5.27-b and up.
