### ISSUE TITLE
[Bug]: Something Odd With The Jack o Lanterns 

### ISSUE THREAD

**Issue by Zaleixx** [cavecomputing/SWEM-Beta#178]
### What happened?

Jack o lanterns look like solid-green colored blocks, and carved pumpkins look yellow when facing a specific direction.

![2022-01-15_23 38 45](https://user-images.githubusercontent.com/91926772/149649150-97c1df9f-f74c-4c75-bd4d-4293ebf1f645.png)

### What should happen?

They shouldn't look like a solid-colored block. 

### Mods

3dSkinLayers-forge-1.1.0
appleskin-forge-mc1.16.x-2.2.0
callablehorses-1.16.3-1.2.1.4
chat_heads_forge-0.2.0
EquipmentCompare-1.16.5-1.2.7
fairylights-4.0.5-1.16.5
geckolib-forge-1.16.5-3.0.35
Hwyla-forge-1.10.11-B78_1.16.2
Iceberg-1.16.5-1.0.24
InventoryHud_[1.16.2-1.16.5].forge-3.4.1
ItemBorders-1.16.5-1.1.2
lootbeams-1.16.5-release-nov0221
OptiFine_1.16.5_HD_U_G8
StorageDrawers-1.16.3-8.3.0
swem-1.16.5-0.2.5.15-b
u_team_core-1.16.5-3.2.1.196
useful_backpacks-1.16.5-1.12.1.90
WailaHarvestability-mc1.16.x-forge-1.1.15
Xaeros_Minimap_21.20.0_Forge_1.16.5
XaerosWorldMap_1.18.1_Forge_1.16.5

### SWEM Version

swem-1.16.5-0.2.5.15-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Can't reproduce on the new beta server. Nothing with SWEM.

I suggest you figure out which mod does this, and report to author :D
