### ISSUE TITLE
[Bug]: lang files keys are incorrect on controls page

### ISSUE THREAD

**Issue by dronade** [cavecomputing/SWEM-Beta#179]
### What happened?

![image](https://user-images.githubusercontent.com/56757680/149829374-2fc87027-c0ae-4608-8590-c320e8378249.png)

### What should happen?

correct text instead

### Mods

modpack v2 

### SWEM Version

swem-1.16.5-0.2.6.0-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This should be fixed with version: `0.2.9.3-b` and up.
