### ISSUE TITLE
SWEM Attribute Potions not working in server

### ISSUE THREAD

**Issue by ShyWoolf** [cavecomputing/SWEM-Beta#181]
With the release of the server, A group of explorers came across many attribute potions, but when they attempt to give it to their horses, they just won't take. Not sure if it is a bug, or a creative mode only trait.

**Comment by ShyWoolf** [comment]
UPDATE! the potions DO WORK! But you only need 1, and it will not be used up.

**Comment by MagnusHJensen** [comment]
This has been fixed with `0.2.6.2-b` and up.
