### ISSUE TITLE
Mounting Horse when using Desensitization Items [Bug]: 

### ISSUE THREAD

**Issue by Stardust312** [cavecomputing/SWEM-Beta#184]
### What happened?

When using the desensitization items on a swem horse you mount the horse.

### What should happen?

When using the desensitization items on swem horse you don't mount the horse.

### Mods

swem-1.16.5-0.2.6.3-b
geckolib-forge-1.16.5-3.0.35

### SWEM Version

swem-1.16.5-0.2.6.3-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Fixed with version: `0.2.7.2-b` and up.
