### ISSUE TITLE
[Bug]: Horse not taming

### ISSUE THREAD

**Issue by Arishant** [cavecomputing/SWEM-Beta#197]
### What happened?

When trying to tame a SWEM horse, nothing happens. Nothing at all. The horse just stands there, does idle anims, and that is it.

### What should happen?

The horse should move around, throw the rider off some, then eventually tame. Basically what it used to be.

### Mods

Latest beta modpack. Only difference is Xaero's worldmap and minimap, as well as optifine.

### SWEM Version

0.3.0.1

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed with version: `0.3.0.2` and up.
