### ISSUE TITLE
Horse gets stuck when falling against a block

### ISSUE THREAD

**Issue by SnowDragon064** [cavecomputing/SWEM-Beta#201]
When you jump or fall onto the side/diagonal of a block, the horse gets stuck(which can be unstuck by letting go of W), and the animations bug out. Tried to recreate to get more images + video but was unable to. Player animations are fine but in the wrong position, and horse animations are stuck below player and extremely jumpy.
![image](https://user-images.githubusercontent.com/84163981/163383835-15e640c6-320a-46a7-bbda-945f2dd4f33c.png)

**Comment by MagnusHJensen** [comment]
This is a limitation from Minecraft when having high speed entities.
