### ISSUE TITLE
[Bug]: Horse still slow falling after taking of amethyst armour. 

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#208]
### What happened?

When you take off the amethyst horse armour off your horse the horse will still have the slow falling effect. The only fix I have found for this is to reload your world or the server you are on.

### What should happen?

The horse should lose the slow falling effect when you remove the armour.

### Mods

v4 Modpack 
Optifine 1.16.5

### SWEM Version

swem-1.16.5-0.3.0.5-b.jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Should be fixed with version: `0.3.2.1-b` and up.
