### ISSUE TITLE
T-pose while riding the horse

### ISSUE THREAD

**Issue by TheSilentHawke** [cavecomputing/SWEM-Beta#209]
### What happened?

While at an extended canter, and only at the extended canter that I've found, when you jump, your horse does the jump animation and goes straight to a t-pose while continuing to move at that gait. It's fixed by galloping or slowing down. 

### What should happen?

The horse should continue the extended canter animation after the jump animation.

### Mods

swem v4 modpack
optifine 1.16.5_HD_U_G8
BetterAnimalModels: betteranimals-1.16.4-5.5.0

### SWEM Version

swem-1.16.5-0.3.1.0-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Should hopefully be fixed with version `0.3.2.0-b` and up.
