### ISSUE TITLE
[Bug]: Level Commands

### ISSUE THREAD

**Issue by RileyCasper** [cavecomputing/SWEM-Beta#213]
### What happened?

Oh boy, this ones a doozy and I don't think any one would have noticed if I wasn't screwing around.

Setting Levels via commands allows you to set outside of restraints.

**Health**
Health can be set to 6 (But not 7), it runs fine, but when you go to open the GUI, it crashes.
![image](https://user-images.githubusercontent.com/80489042/169687519-8c16682e-f3c6-4e56-bb4c-52cef68faa6d.png)
7 threw the incorrect level range.

**Jump**
Jump gives an unexpected error.
![image](https://user-images.githubusercontent.com/80489042/169687597-a2afd8e7-289b-433f-b9c1-361b1e749c54.png)

**Speed**
Speed appears to be fine, and gives the proper error code.
![image](https://user-images.githubusercontent.com/80489042/169686529-540d99de-3723-4398-b628-790db5b6c590.png)

**Affinity**
Affinity appears to be fine, and gives the proper error code.
![image](https://user-images.githubusercontent.com/80489042/169686466-8485e4b2-f6da-40ba-9862-8faea7f67645.png)

**All**
All Stats gives a similar to jump as an unexpected error.
![image](https://user-images.githubusercontent.com/80489042/169687667-4c7bb608-dc80-4c07-82c3-f02b73d7411e.png)

### What should happen?

Health shouldn't be able to be set above 5 and give a similar error code to Speed and Affinity.
Jump's error return should probably be similar to speed and affinity.
All is kinda a questionable one since Affinity is included in that. I'm not sure where that should go.

### Mods

SWEM Beta
Geckolib
Optifine

**Was found in a large modpack but then tested with just SWEM**

### SWEM Version

0.3.1.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [X] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
I don't feel like a log is required, Since it's exactly as legend stated in discord.

IndexOutOfBounds is the crash that occurs.
```

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `0.3.2.2-b` and up.
