### ISSUE TITLE
[Bug]: Amethyst Armor Upsidedown

### ISSUE THREAD

**Issue by WildSilverr** [cavecomputing/SWEM-Beta#218]
### What happened?

While riding a horse, amethyst armor appears upside down
![image_2022-07-05_212758367](https://user-images.githubusercontent.com/93545930/177454794-2bc1d3d7-78e4-4fef-9065-6e044446b0ff.png)

### What should happen?

Armor should appear rightside up and proper on the minecraft avatar model

### Mods

![image_2022-07-05_212926804](https://user-images.githubusercontent.com/93545930/177454999-b53d66ae-522d-4712-b37a-a0ee53b16c03.png)

### SWEM Version

swem 1.16.5-0.3.6.2-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This was fixed with the introduction of a new player animation lib.
