### ISSUE TITLE
[Bug]: Frozen front right leg

### ISSUE THREAD

**Issue by WildSilverr** [cavecomputing/SWEM-Beta#219]
### What happened?

While riding, the front right leg is stiff as a board. The ankle moves but the knee does not bend in any gaits, jumps or refusal animations. 
![image_2022-07-05_213906098](https://user-images.githubusercontent.com/93545930/177456187-5fc3122b-4980-4057-b86d-2941505e1d61.png)

https://user-images.githubusercontent.com/93545930/177459391-8b5b0561-d3c9-4b94-a7c5-bb575089d453.mp4

https://user-images.githubusercontent.com/93545930/177459527-db1c0a02-1764-4ef4-bb21-c3ee039d638a.mp4

### What should happen?

The leg should animate itself fully, knee bending and proper stride

### Mods

![image_2022-07-05_220857009](https://user-images.githubusercontent.com/93545930/177459660-180f2ec1-6edd-400e-aa89-de57db356e5b.png)

### SWEM Version

swem 1.16.5-0.3.6.2-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This has been fixed with `0.3.6.3-b`
