### ISSUE TITLE
[Bug]: A few item names are messed up.

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#224]
### What happened?

I have noticed that the block o' water and the tack box's names show up a block.swem.block_o_water and block.swem.tack_box_(then the colour). I think these are the only two but there could be more.

### What should happen?

The names should appear like all the others.

### Mods

What ever is on the server as of release of the latest version along with the latest versions of SWEM and Gekolib

### SWEM Version

0.4.0.0

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed in 0.4.1.0
