### ISSUE TITLE
[Bug]: Lead is in two places?

### ISSUE THREAD

**Issue by BrookWithAnE3** [cavecomputing/SWEM-Beta#227]
### What happened?

A lead shows up on the horse and away from the horse. It happens with both the lead and anchor
![2022-08-06_11 11 56](https://user-images.githubusercontent.com/104723616/183255033-5bb368f0-ab4c-4e16-b895-510af2e97d7d.png)
![2022-08-06_11 12 10](https://user-images.githubusercontent.com/104723616/183255036-af9213e6-c925-4e86-bf2f-7f234d12261b.png)
.

### What should happen?

Only be one lead connected to player. 

### Mods

Required Mods

### SWEM Version

0.4.0.0

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed with the next update `0.4.2.0`
