### ISSUE TITLE
[Bug]: Locker names messed up.

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#228]
### What happened?

When you open on of the sides of the locker, the name at the top of the locker gui shows as container.swem.locker.left and container.swem.locker.right.

### What should happen?

I think it should just say left locker and right locker.

### Mods

I am playing on the V2 Beta server.

### SWEM Version

swem-1.16.5-0.4.0.0-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed in 0.4.1.0
