### ISSUE TITLE
Jumping Rails

### ISSUE THREAD

**Issue by Hannahmarie19** [cavecomputing/SWEM-Beta#23]
### What happened?

Jumping rails don't line up, not pictured grain feeders don't place
![2021-11-03 (2)](https://user-images.githubusercontent.com/93631826/140191998-69cb849c-4c84-42cd-9462-cdea50db724c.png)
p

### What should happen?

Rails should line up

### Mods

SWEM and geckolib

### SWEM Version

SWEM-1.16.5-0.1.0.1-b_1

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by 2004crystal** [comment]
I had this happen as well!

**Comment by livboo222** [comment]
This is happening to me too D:

**Comment by livboo222** [comment]
> I had this happen as well!

Were you able to fix it?

**Comment by vividlyindigo** [comment]
you need to be facing the way you're jumping when using the measuring tool to make jumps! This questions was also answered in the discord, ask there for further support:)
