### ISSUE TITLE
[Bug]: Horses dont take fall damage when wearing armoured blanket

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#236]
### What happened?

When I dropped my tamed horse from a height wearing an armoured horse blanket, it didnt take fall damage. It doesnt happen when using the normal blankets.

### What should happen?

They should take fall damage.

### Mods

It was on the V2 Beta server

### SWEM Version

swem-1.16.5-0.4.0.0-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
It's intended for Pasture Blankets Armoured to have Amethyst effects for now.
