### ISSUE TITLE
[Bug]: Players Merging

### ISSUE THREAD

**Issue by ShyWoolf** [cavecomputing/SWEM-Beta#237]
### What happened?

When two players mount a horse, they merge together
![2022-08-08_12 59 27](https://user-images.githubusercontent.com/93551814/183483617-3efed8a4-4f4e-4fac-a410-94ed598381e6.png)

### What should happen?

Two players should line up instead of merging

### Mods

Beta Server
- JEI Extentions
- Replay Mod (Disabled)
- Optifine

### SWEM Version

Swem 0.4.0.0-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed with 0.4.2.0
