### ISSUE TITLE
[Bug]: All horse armour disappear when you place a block coming off the armour rack.

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#248]
### What happened?

When you place any SWEM horse armour on the rack and look at the side and place a block the armour disappears. along with the block.

### What should happen?

The armour and block should stay.

### Mods

It was on the Beta server.

### SWEM Version

swem-1.16.5-0.4.1.0-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed with version `0.4.9.3` and above.
