### ISSUE TITLE
[Bug]: Horse walks in air!

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#249]
### What happened?

When you pull a horse into the sky using a lead and move around it does the walking animation.

### What should happen?

I think the horse should stand still.

### Mods

It was on the Beta server.

### SWEM Version

swem-1.16.5-0.4.1.0-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed with `0.4.9.3` and above.
