### ISSUE TITLE
[Bug]: animations stay even after stopping

### ISSUE THREAD

**Issue by emafema** [cavecomputing/SWEM-Beta#255]
### What happened?

when stopping the horse - the animation should also stop :D

https://user-images.githubusercontent.com/93468469/184996214-f5fe265a-6925-456f-b19e-a4920361989f.mov

 

### What should happen?

when the horse stops the rider animation should aswell

### Mods

![Skärmavbild 2022-08-17 kl  00 30 34](https://user-images.githubusercontent.com/93468469/184996351-d4eff1e7-00a1-4caa-b811-474ebf530fca.png)
![Skärmavbild 2022-08-17 kl  00 30 15](https://user-images.githubusercontent.com/93468469/184996352-20c429cd-c647-47bf-ad2d-c2e7e2d44547.png)

### SWEM Version

0.4.3.0-b aswell as the play animation tester

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Mac

**Comment by MagnusHJensen** [comment]
Fixed with 4.4.2
