### ISSUE TITLE
Horse animation breaks after riding

### ISSUE THREAD

**Issue by YourFriendlySpaghetti** [cavecomputing/SWEM-Beta#26]
### What happened?

I was riding my horse, it refused to go faster and then its animation broke and started sliding across the grass
![2021-11-03_21 11 52](https://user-images.githubusercontent.com/93439372/140193582-271c2f19-5622-41ad-9acc-466ce37a1e25.png)
.

### What should happen?

After a horse refuses to go faster it should slow down!

### Mods

Swem 1.16.5 Gecklib

### SWEM Version

1.01

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This should have been fixed with newer versions.
