### ISSUE TITLE
[Bug]: Healing items cause player to be mounted on horse

### ISSUE THREAD

**Issue by flokii7** [cavecomputing/SWEM-Beta#263]
### What happened?

When using healing items (salve, bandage, medicated bandage) player temporarily mounts horse then is automatically dismounted. After this, if shift is clicked the player is teleported back next to the horse as if they have just dismounted.

https://user-images.githubusercontent.com/86190898/190916773-19f30c5a-d60e-40c1-8e91-97fac8c58031.mp4

### What should happen?

Pressing shift after should not teleport the player

### Mods

![image](https://user-images.githubusercontent.com/86190898/190916850-dab6012a-d249-410c-be0e-23f87ed05ab0.png)

### SWEM Version

swem-1.16.5-0.4.9.0-b

### Singleplayer or Multiplayer

- [ ] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed with version: `0.4.9.8` and above,
