### ISSUE TITLE
[Bug]: Horse Drowning

### ISSUE THREAD

**Issue by burning-brightly** [cavecomputing/SWEM-Beta#27]
### What happened?

I got off my horse in the middle of the ocean and swam down to look at something in the water. When I came back up my horse was sinking, so i switched to creative mode to try and save it but when i grabbed it with a lead nothing happened and it kept taking damage

### What should happen?

The horse should either follow the lead or swim to the top itself

### Mods

just swem

### SWEM Version

1.16.5-0.1.0.1

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by burning-brightly** [comment]
It's not even taking damage anymore, its just suspended in the ocean and floating under water bucking around as if its taking damage

**Comment by burning-brightly** [comment]
One more thing- horses and players do not take fall damage

**Comment by lulupisita** [comment]
also had the same bug!
video is too big but I will put it on discord!

**Comment by MagnusHJensen** [comment]
This is fixed with version: `0.1.2.1-b` and up.
