### ISSUE TITLE
water through

### ISSUE THREAD

**Issue by HolyFoal** [cavecomputing/SWEM-Beta#28]
### What happened?

when placing the double water through, right one first, then filling it up with water, it turns the left one to a half through, and the right one to a single.

### What should happen?

the water should've filled both normally.

### Mods

swem geckolib

### SWEM Version

0.1.0.1-b_1

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Silverwolf11420** [comment]
I've had the same problem.
![2021-11-03_19 04 19](https://user-images.githubusercontent.com/70761126/140236111-ea820014-a243-4306-9d3d-96384c50aa92.png)
![2021-11-03_19 04 31](https://user-images.githubusercontent.com/70761126/140236114-1c5823a5-6d7b-4876-8555-7878ccea812c.png)
Steps to reproduce
1. Place water trough down in a corner, fill with water
2. Place down another water trough next to it then right click the 1st trough (splits, 1st picture)
3. Place a new water trough anywhere else from the current ones and it'll show the second picture

swem
geckolib

Swem version - 0.1.0.2-b

Singleplayer
OS- Windows

**Comment by MagnusHJensen** [comment]
This is fixed with version: `0.1.3.13-b` and up.
