### ISSUE TITLE
[Bug]: Game crashing

### ISSUE THREAD

**Issue by Hehe243** [cavecomputing/SWEM-Beta#287]
### What happened?

The game crashes whenever I try to join a world

### What should happen?

The game should run smoothly

### Mods

Swem mod (1.16.5)
Player Animation mod (1.16.5)
Geckolib mod (1.16.5)

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Mothfet** [comment]
I literally cannot do anything about this without a crash log. We are not psychic; please include one next time. It is in the bug report instructions.
