### ISSUE TITLE
[Bug]: using /swem wild on a horse without tack puts a set of grey western tack on said horse

### ISSUE THREAD

**Issue by vividlyindigo** [cavecomputing/SWEM-Beta#301]
### What happened?

Mounting a horse with no tack and use "/swem wild" causes tack to magically appear in the horse's inventory (I was in creative mode, did not try in survival). You can take the tack off and run the command again and it repopulates with more tack— however, it seems to always be a set of western gray tack

### What should happen?

I want the law of conservation of matter to be followed even in pixel horse game and not have random tack spawning out of nowhere /lh

thanks team XD

### Mods

SWEM 1.16.5-0.5.1.0
(w/ player animations, gekolib)
SWDM 1.16.5-2.0.2 (most likely is not affecting the bug)

### SWEM Version

SWEM 1.16.5-0.5.1.0

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Mac

**Comment by MagnusHJensen** [comment]
This is an intended feature of the `/swem wild` command.

It was specifically made for filming purpose, so might not bring that much value to regular players.

**Comment by vividlyindigo** [comment]
ooh okay, thanks, MagnusHJensen!
