### ISSUE TITLE
[Bug]: Game crashes when foal grows up

### ISSUE THREAD

**Issue by xukura** [cavecomputing/SWEM-Beta#319]
### What happened?

The game crashed once the foal grew up. In the exact moment the foal had grown up, I was placing a sign. The game froze for ~20 seconds before crashing and giving exit code -1.

### What should happen?

The game shouldn't crash.

### Mods

![image](https://user-images.githubusercontent.com/114314524/192118805-4949fce3-dda3-429e-9c2d-57a4b17e1d6d.png)

### SWEM Version

1.16.5-0.5.0

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
https://pastebin.com/9J0egEKH
```

**Comment by MagnusHJensen** [comment]
Fixed with version `0.5.2.0` and above.
