### ISSUE TITLE
[Bug]: Items not appearing in locker

### ISSUE THREAD

**Issue by Neonrift** [cavecomputing/SWEM-Beta#33]
### What happened?

Occasionally when you click on a locker the items inside don't show.

### What should happen?

Items should show everytime you click on the locker

### Mods

SWEM
Geckolib

### SWEM Version

0.1.0.0-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by its-jennie** [comment]
I think that the lockers have two sides so it is dependent on where you click and which locker you select to open.

**Comment by MagnusHJensen** [comment]
The lockers have 2 "chest" inventories, one on either side "defined by the panels in front".

So you basically get a double chest within one block, but it's separated by where you click on the block.

If the issue persists, hitting the same side, please reopen.
