### ISSUE TITLE
[Bug]: Horse doesn't take fall damage

### ISSUE THREAD

**Issue by Shrimpez** [cavecomputing/SWEM-Beta#36]
### What happened?

Horse is immune to any sort of fall damage (in creative and survival)
Doesn't matter if being pushed or ridden off a cliff no dqamage is taken

### What should happen?

Horse should ideally lose health

### Mods

Just SWEM

### SWEM Version

1.16.5-0.1.0.2-b.jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by cavecomputing** [comment]
This is probably from some internal testing we were doing that was left over. Does the player character also take fall damage off of a horse?

**Comment by MagnusHJensen** [comment]
This is fixed and re-added with version: `0.2.5.0-b` and above.
