### ISSUE TITLE
[Bug]: Multiple Troughs Next to Each other Crashes Game

### ISSUE THREAD

**Issue by TheSilentHawke** [cavecomputing/SWEM-Beta#39]
### What happened?

When placing 3 troughs beside eachother, a 4th trough, when placed behind one of the three, crashes the game.

### What should happen?

It should either allow me to place it, or not allow me to place it.

### Mods

SWEM, GeckoLib

### SWEM Version

swem-1.16.5-0.1.0.2-b.jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=two_way, clazz=class com.alaharranhonor.swem.blocks.SWEMBlockStateProperties$TwoWay, values=[single, left, middle, right]} as it does not exist in Block{minecraft:oak_log}
Exit Code: -1
```

**Comment by MagnusHJensen** [comment]
This should be fixed with `0.1.3.0-b` and up.
