### ISSUE TITLE
[Bug]: Bridle floating?

### ISSUE THREAD

**Issue by Dashhound171** [cavecomputing/SWEM-Beta#4]
### What happened?

A bug happened!

### What should happen?

The bridle looks glitched out when riding horse

### Mods

SWEM

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Joequidae** [comment]
I think I have this too, heres a SS: 
![image](https://user-images.githubusercontent.com/93680345/140183305-29be377a-5049-473a-ac86-b71637de2956.png

**Comment by Xemoness** [comment]
I have the bug as well.
![2021-11-03_20 56 32](https://user-images.githubusercontent.com/93418199/140183488-28f9d7c8-1f66-410b-bd3a-207cf9dc339a.png)

**Comment by bearteeths** [comment]
This happens me as well!

**Comment by MagnusHJensen** [comment]
This is fixed with version: `1.16.5-0.1.0.1-b` and up.
