### ISSUE TITLE
[Bug]: Grain feeder Missing Texture

### ISSUE THREAD

**Issue by Sarahistired** [cavecomputing/SWEM-Beta#41]
### What happened?

When I placed the grain feeder it came up with a purple and black block.

### What should happen?

It should place the grain feeder

### Mods

SWEM, Geckolib

### SWEM Version

Newest release

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by cavecomputing** [comment]
Noticed the first ticket mentioning this on page 2. Closing this as dup of issue https://github.com/cavecomputing/SWEM-Beta/issues/9

**Comment by deerhotel** [comment]
Also experiencing this issue on a Mac Big Sur
