### ISSUE TITLE
[Bug]: No Fall Damage (Player and Horse)

### ISSUE THREAD

**Issue by cavecomputing** [cavecomputing/SWEM-Beta#42]
### What happened?

SWEM disables all fall damage regardless if you are on a horse or not. 

### What should happen?

Player should receive fall damage on falling

### Mods

Mod in use is older version: swem-1.16.5-0.25.3.0-Alpha_3.jar
geckolib-forge-1.16.5-3.0.35.jar

Fall damage is still disabled on newer versions though as per response from Hannah. 

### SWEM Version

swem-1.16.5-0.25.3.0-Alpha_3.jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [X] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by cavecomputing** [comment]
Awaiting response from other ticket: https://github.com/cavecomputing/SWEM-Beta/issues/36
Closing that ticket if same scenario as this.

**Comment by MagnusHJensen** [comment]
This is fixed and re-added with version: `0.2.5.0-b` and above.
