### ISSUE TITLE
[Bug]: Water Trough Causes Crash

### ISSUE THREAD

**Issue by TescoTimeiSwag** [cavecomputing/SWEM-Beta#43]
### What happened?

I place a water trough but I fill it and it splits like a double trough but with one side and if you try and place a new one it kicks you

### What should happen?

A water trough that dosnt kick you.

### Mods

Swem: 1.16.5-0.1.0.2-b jar 

### SWEM Version

1.16.5-0.1.0.2-b jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by cavecomputing** [comment]
Similar to issue https://github.com/cavecomputing/SWEM-Beta/issues/39 but not the same cause

**Comment by MagnusHJensen** [comment]
Closing as this looks like a similar cause, not directly identical, but still.

Let me know if this still happens on versions above `0.1.3.13-b` and up.
