### ISSUE TITLE
[Bug]: Horse Getting Stuck on Cactus

### ISSUE THREAD

**Issue by XxLuviexX** [cavecomputing/SWEM-Beta#47]
### What happened?

While exploring the desert on my horse, I accidentally went over a cactus. The horse then got stuck on top of the cactus and began taking damage. It would not let me move the horse until I dismounted and pushed it. 

### What should happen?

Preferably, the horse would be able to move off the cactus, rather than being stuck on it, as this could lead to an accidental death.

### Mods

SWEM, Gecko

### SWEM Version

Newest release

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by Silverwolf11420** [comment]
I have the same problem 
SWEM Version - 0.1.2.1-b

**Comment by MagnusHJensen** [comment]
This should be fixed with version `0.1.6.13-b` and up.
