### ISSUE TITLE
Auto Jumping Won't Disable / Riding Shoes Update

### ISSUE THREAD

**Issue by Hannahmarie19** [cavecomputing/SWEM-Beta#48]
### What happened?

Even when not on the horse there is no falling damage, also noticed player auto jumping onto blocks even with auto jump disabled

### What should happen?

Should have fall damage and shouldn't auto jump unless setting is on.

### Mods

SWEM and Geckolib

### SWEM Version

0.1.0.2-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by cavecomputing** [comment]
Renamed as dup of issue: https://github.com/cavecomputing/SWEM-Beta/issues/42
This ticket will focus on the auto jumping bug once confirmed it is indeed a bug with SWEM, although I was able to test this myself and did no have a problem with auto jumping. I have it set as disabled and it is disabled as it should be. 

geckolib-forge-1.16.5-3.0.35.jar
swem-1.16.5-0.1.0.2-b.jar

**Comment by Hannahmarie19** [comment]
I tried a few things, noticed only occurs while wearing the new riding shoes!

**Comment by cavecomputing** [comment]
Confirmed. It doesn't say in the description but this is intentional behavior (I wasn't aware of it). I'll pass this on to @MagnusHJensen and see if we can update the description so that it says that's what it does

**Comment by MagnusHJensen** [comment]
Leather Riding boots give you one-step (So like auto-jump but without the jump)
Amethyst boots disables fall damage. 
These are perks of the different tier boots, I will look into adding descriptions to the items.

**Comment by MagnusHJensen** [comment]
I have added descriptions to the boots as of version: `0.1.3.6-b` and up.
