### ISSUE TITLE
[Bug]: Not being able to place stall doors

### ISSUE THREAD

**Issue by Dashhound171** [cavecomputing/SWEM-Beta#50]
### What happened?

I'm unable to place certain stall doors (horse doors) in a 2x1 area. No shavings, no blocks, no nothing is in the way. It places on the block behind it but not where I actually need it. 

### What should happen?

The doors should place normally

### Mods

1.0.2-b SWEM

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Insufficient information, not sure what you mean.
I can place them normally.
Try and include a video of you trying to place it, or a screenshot of the space you are trying to place it at.
