### ISSUE TITLE
[Bug]: items dissapearing

### ISSUE THREAD

**Issue by Cheesecak3uwu** [cavecomputing/SWEM-Beta#52]
### What happened?

i put a saddle on the saddle rack and when i tried to remove it, the item disappeared. this has happened with halters on the halter rack, and leads on the hitching post. 

### What should happen?

player should receive the items back instead of the items disappearing.

### Mods

Gecklib3 3.0.35

### SWEM Version

1.0.2-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This how creative mode often works.
To not clog up inventory, if you are creative it just makes the items dissappear.
If you were in survival, please reopen the issue.
