### ISSUE TITLE
[Bug]: All XP Bottle not working

### ISSUE THREAD

**Issue by EvenBlutoms** [cavecomputing/SWEM-Beta#53]
### What happened?

All XP Bottle not working, tried other horses and nothing. Other XP Bottles had worked but the All XP Bottle.

### What should happen?

Giving all horse' stats XP

### Mods

SWEM
geckolib

### SWEM Version

1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
No Response
```

**Comment by Aizicle** [comment]
I have the same problem!

**Comment by MagnusHJensen** [comment]
I can't seem to reproduce, I get a 50+ in all stats, when using the All XP bottle.
Re open with a video showing that it doesn't work.
