### ISSUE TITLE
[Bug]: Breaking racks like horse armor rack

### ISSUE THREAD

**Issue by Athenacat16** [cavecomputing/SWEM-Beta#54]
### What happened?

When you break the bridle rack, saddle rack and horse armor rack they break as purple and black
![Block breaking wrong](https://user-images.githubusercontent.com/93494266/140244749-def0cb8a-0e3c-4f64-a1a9-8d2141b977cb.png)

### What should happen?

they should break as the color of the block

### Mods

SWEM
geckolib

### SWEM Version

1.16.5 1.0.2-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This has been fixed with version: `0.2.2.17-b` and up.
