### ISSUE TITLE
[Bug]: Tack Box's phasing into walls (specifically fences)

### ISSUE THREAD

**Issue by Phoenix615266** [cavecomputing/SWEM-Beta#58]
### What happened?

I was trying to place tack trunks, and accidentally phased it into my wall. Now my property value has gone down. (put video in the discord)

### What should happen?

Tack trunks shouldn't phase into walls.

### Mods

SWEM- 1.16.5 0.1.0.1
geckolib- 1.16.5 3.0.35

### SWEM Version

0.1.0.1 1.16.5

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This is fixed with version: `0.1.1.4-b` and up.

So I hope you can go and get your property value back up ;)
