### ISSUE TITLE
[Bug]: Gates and lockers

### ISSUE THREAD

**Issue by BopBoptheBop** [cavecomputing/SWEM-Beta#61]
### What happened?

When opening a chest/locker/barrel while holding a stall door/gate, the gate/door will place and glitch when you try to destroy it by dividing into 4 parts forcing you to break all four parts. I know this is something you could easily just say not to do but I wanted to point it out.

### What should happen?

It should not get placed at all.

### Mods

Just SWEM

### SWEM Version

V1

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
I can't seem to see any issues with chests/barrels, I do however see the issue with the locker.

**Comment by MagnusHJensen** [comment]
This is fixed with version: `0.1.0.4-b` and up.
