### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PotatoMum** [cavecomputing/SWEM-Beta#63]
### What happened?

When equipping a saddle onto a horse and then riding on said horse after a few seconds i would jump off and the saddle would be unequipped from the horse and would appear back in my inventory

### What should happen?

i should be able to leave said saddle on and be able to rise the horse without it coming off all of a sudden

### Mods

SWEMS-1.16.5 0.1.0.2
Geckolib-forge-1.16.5

### SWEM Version

0.1.0.2

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This sounds like our intended game play feature.
