### ISSUE TITLE
[Bug]: Stable door not opening

### ISSUE THREAD

**Issue by Yvai1149** [cavecomputing/SWEM-Beta#67]
### What happened?

Whenever I use the stable doors they stop working after a couple of uses. They don't open anymore

### What should happen?

They should keep working

### Mods

SWEm
Geckolib

### SWEM Version

0.1.0.2-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Are you placing anything where it's supposed to open?

Iccan't reproduce, please reopen with steps to reproduce and include screenshots.
Also reopen if this still happens on newer versions.
