### ISSUE TITLE
[Bug]: Horses On Fire Freeze (So no lava swimming)

### ISSUE THREAD

**Issue by fatherjenny** [cavecomputing/SWEM-Beta#74]
### What happened?

Whenever the horse's set fire - in a fire or lava - they either loop rear in pain or just freeze idled. No swimming, no moving them away.

### What should happen?

They should be able to swim in lava and run away from a flame. They also shouldn't burn in amethyst armour.

### Mods

SWEM
Gecko
Xaeros world+minimap

### SWEM Version

0.1.1.0-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This stuck in "pain loop" should be fixed with version `0.1.6.13-b` and up.
