### ISSUE TITLE
[Bug]: jump poles facing incorrectly

### ISSUE THREAD

**Issue by flokii7** [cavecomputing/SWEM-Beta#75]
### What happened?

![Screenshot (12)](https://user-images.githubusercontent.com/86190898/140415144-07b5f3b9-6169-411b-93fb-25b487f1b94a.png)
Blue panel arrow jump pole not facing correctly when jump is set to 5 blocks high.

### What should happen?

The first block of the panel arrow pole should face the correct direction.

### Mods

Geckolib 3.0.35
SWEM 0.1.1.1

### SWEM Version

1.16.5-0.1.1.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by PygmyFalcon** [comment]
I didn't make a separate bug report because I saw this one, but none of my jumps lined up correctly. All the pieces were sideways no matter what direction.
![2021-11-04_21 39 35](https://user-images.githubusercontent.com/93748996/140443939-6ac6f400-f05e-42cc-b1d9-d19edb4f7f8f.png)

**Comment by flokii7** [comment]
You have to make sure you face the jump the same way as if you were about to jump over it, they should align correctly that way.

**Comment by flokii7** [comment]
> I didn't make a separate bug report because I saw this one, but none of my jumps lined up correctly. All the pieces were sideways no matter what direction.
> 
> ![2021-11-04_21 39 35](https://user-images.githubusercontent.com/93748996/140443939-6ac6f400-f05e-42cc-b1d9-d19edb4f7f8f.png)
> 
>  
> 
> 

You have to make sure you face the jump the same way as if you were about to jump over it, they should align correctly that way.

**Comment by MagnusHJensen** [comment]
OP's issue is fixed with version: `0.2.2.10-b` and up.
