### ISSUE TITLE
[Bug]: Not able to craft refined leather.

### ISSUE THREAD

**Issue by 2by2withnoah** [cavecomputing/SWEM-Beta#77]
### What happened?

The crafting recipe for refine leather doesnt appear in the recipe book even though i have the right items nor can i craft it just placing the items in the grid.

### What should happen?

I should be able to craft it or see the recipe.

### Mods

GekoLib
Swem

### SWEM Version

swem-1.16.5-0.1.1.1-b.jar

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
I can't seem to reproduce.

![image](https://user-images.githubusercontent.com/32039051/140481502-e0dbd5fd-5b1f-4192-91e8-12858fc51e82.png)

**Comment by 2by2withnoah** [comment]
Ok i will try that.
