### ISSUE TITLE
[Bug]: Horse Texture lost after several relogs

### ISSUE THREAD

**Issue by its-jennie** [cavecomputing/SWEM-Beta#78]
### What happened?

I was changing my skin and had a black SWEM horse, after a few relogs I then went to look at the horse and found it to be blue as shown below. When I used the lapiz lazuli on it to change the colour back it also went another coat with several colours which I'm guessing was what one of the coats used during coding before other coats were added. I forgot to take a screenshot but it did return to the normal coat variations after this.

![2021-11-04_20 54 46](https://user-images.githubusercontent.com/93680012/140419389-ea04ba7f-e942-4642-a254-d7b90a8997b3.png)

### What should happen?

The horse was originally black.

### Mods

SWEM 1.16.5 0.1.1.1.b
geckolib3 3.0.35

### SWEM Version

 0.1.1.1.b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Duplicate #73
