### ISSUE TITLE
[Bug]: Horse stuck in water/not swimming

### ISSUE THREAD

**Issue by Arishant** [cavecomputing/SWEM-Beta#8]
![2021-11-03_15 57 18](https://user-images.githubusercontent.com/59959986/140184581-8d7d0d6d-be9f-4d96-8bca-1af7ec07af7f.png)
### What happened?

If you dismount a horse in the water, it sinks, and then proceeds to keep sinking until it becomes stuck in a constant state of bucking. Horse cannot be led away from water or mounted, even before the bucking started.

### What should happen?

I expected the horse to keep swimming or to swim towards shore. Or if it started to sink, to be able to lead it out of the water.

### Mods

Just SWEM and geckolib.

### SWEM Version

swem-1.16.5-0.1.0.0-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
This was fixed in version: `0.1.2.1-b` and up.
