### ISSUE TITLE
[Bug]: Already reported please ignore. My apologies!

### ISSUE THREAD

**Issue by haileeebyrd** [cavecomputing/SWEM-Beta#86]
### What happened?

My game crashed from the SWLM bug I just reported and then I come back to a blue horse and all my other horses coats were changed to ones that I didn't have initially 

### What should happen?

Horses should stay the same color. One of the horses should be blue.
![image](https://user-images.githubusercontent.com/93362766/140454766-1364185f-1c37-452f-aab9-b41abfaa9311.png)

### Mods

SWEM
SWLM
Geckolib

### SWEM Version

1.16.5-0.1.1.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by MagnusHJensen** [comment]
Duplicate #73
