### ISSUE TITLE
[Bug]: Lockers poof items in them

### ISSUE THREAD

**Issue by Joequidae** [cavecomputing/SWEM-Beta#87]
### What happened?

sometimes when opening a locker after already having put items inside of it, the items have vanished. if you esc and re-open it a few times over, they come back.

### What should happen?

the items should stay where they are in the locker

### Mods

geckolib forge 3.0.35

swem 0.1.1.1-b

### SWEM Version

0.1.1.1-b

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

**Comment by flokii7** [comment]
There are two sides of a locker, depending on which door you right click it will open two different inventories, this may be the problem that you're facing.

**Comment by MagnusHJensen** [comment]
Duplicate #33
