### ISSUE TITLE
[Bug]: Cannot feed horses

### ISSUE THREAD

**Issue by PygmyFalcon** [cavecomputing/SWEM-Beta#99]
### What happened?

No food item or combination of food items increases horse hunger. I have tried feeding my horses wheat, oat bushel, timothy bushel, alfalfa bushel, carrots, sugar cube, apple, sweet feed, etc. Basically any reasonable edible item. 

I also left out a slow feeder which the horse ignored. Same with water troughs, but I can give my horse buckets of water by hand to increase the water.

Note: by hand means by clicking on the mob in this situation.
[debug.log](https://github.com/cavecomputing/SWEM-Beta/files/7489287/debug.log)
 

### What should happen?

The horse should either be able to eat from the feeders or by hand. Basically stop horses from having no choice but to starve

### Mods

![neigh2](https://user-images.githubusercontent.com/93748996/140588247-8f3f4ad8-3741-491f-a018-422081c31720.PNG)

### SWEM Version

swem-1.16.5-0.1.2.1-b.

### Singleplayer or Multiplayer

- [X] Singleplayer
- [ ] Multiplayer
- [ ] Other (Please add a comment to the issue where this is happening)

### OS

Windows

### Relevant log output

```shell
Debug log uploaded to what happened.
```

**Comment by MagnusHJensen** [comment]
The automatic looking for food, will be fixed with next release, however 0.1.3.0 fixed a issue where hunger would instantly go down after upping a level.

Closing as this is a combination of those two things.
